"""add_chat_messages_table

Revision ID: 2f88213b28af
Revises: cfde073c74a1
Create Date: 2025-11-18 12:52:57.141119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f88213b28af'
down_revision: Union[str, None] = 'cfde073c74a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_created', 'chat_messages', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_customer_id'), 'chat_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='customers')
    op.drop_index(op.f('ix_users_id'), table_name='customers')
    op.drop_index(op.f('ix_users_username'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=True)
    op.drop_constraint(op.f('terraform_jobs_customer_id_fkey'), 'terraform_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'terraform_jobs', 'customers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terraform_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('terraform_jobs_customer_id_fkey'), 'terraform_jobs', 'customers', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_users_username'), 'customers', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'customers', ['email'], unique=True)
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_customer_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index('idx_customer_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
