"""Init

Revision ID: cfde073c74a1
Revises: 
Create Date: 2025-11-17 10:32:17.198934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfde073c74a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='customers')
    op.drop_index(op.f('ix_users_id'), table_name='customers')
    op.drop_index(op.f('ix_users_username'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=True)
    op.drop_constraint(op.f('terraform_jobs_customer_id_fkey'), 'terraform_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'terraform_jobs', 'customers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terraform_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('terraform_jobs_customer_id_fkey'), 'terraform_jobs', 'customers', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_users_username'), 'customers', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'customers', ['email'], unique=True)
    # ### end Alembic commands ###
